#pragma once

#define BACKTYPE_NAME "BackType"
#define BACKTYPE_MATCH_NAME "jx.BackType"
#define BACKTYPE_CATEGORY "jx plugins"

#define BACKTYPE_VERSION_MAJOR 0
#define BACKTYPE_VERSION_MINOR 1
#define BACKTYPE_VERSION_PATCH 3
#define BACKTYPE_VERSION_BUILD 1
